Add eleve id in json filenames
hacf-fr/hass-ecoledirecte pull request #32
Opened 2024-09-25 09:25 UTC by ctournayre

Ajout des id des élèves dans le nom des json afin qu'ils ne soient pas écrasés en cas de plusieurs enfants

2024-09-27 17:14 UTC, Giga77 requested changes
Pour le commit [30d5ba7](https://github.com/hacf-fr/hass-ecoledirecte/pull/32/commits/30d5ba7ea1944b0883f854a38e04b74f75825527), je trouve que changer un ID technique n'apporte rien, et complexifie le code.
Peux-tu supprimer ce commit de la PR ?

2024-09-30 07:03 UTC, ctournayre commented
C'est supprimé

2024-09-30 21:06 UTC, Giga77 commented
> C'est supprimé

Non, tu t'es trompé dans le revert...

2024-10-01 08:21 UTC, ctournayre commented
Voila cette fois c'est bon, désolé.

2024-10-01 18:21 UTC, Giga77 approved these changes

2024-10-01 18:48 UTC, merged